### ISSUE TITLE
Links with query parameters are considered invalid

### ISSUE THREAD

**Issue by morekid** [HiDeoo/starlight-links-validator#63]
### Is your feature request related to a problem?

I have a site with Astro output set to `static` but I am consuming query parameters with JS on the client. For this reason I'm adding query params to the links in the markdown body, however the build is failing because links such as `/docs/some-doc?p=value` are considered invalid.

### Describe the solution you'd like

I'd like a way to successfully validate such links. Ideally a configuration option where I can allow query parameters for specific link patterns.

### Describe alternatives you've considered

Alternatively, the ability to add a custom parser to validate links matching specific patterns.

### Additional Context

Currently I can use an [`exclude`](https://starlight-links-validator.vercel.app/configuration/#exclude) pattern to fix the build but I'd like to be able to still validate the part of the link without the query string.

**Comment by HiDeoo** [comment]
Thanks for your feedback, definitely a use case that I didn't hit or even think about.

> Currently I can use an [`exclude`](https://starlight-links-validator.vercel.app/configuration/#exclude) pattern to fix the build but I'd like to be able to still validate the part of the link without the query string.

This makes total sense. This should now be fixed in the version [`0.12.3`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.12.3) that I just published.

**Comment by morekid** [comment]
@HiDeoo thanks for looking into this, however the validation is still failing with the same error.

```
 validating links
13:06:28 [ERROR] ✗ Found 6 invalid links in 3 files.
13:06:28 ▶ some-page/
13:06:28   ├─ ?f=bun - invalid hash
13:06:28   ├─ /docs/some-doc?p=value - invalid link
...
```
