### ISSUE TITLE
False 'invalid link' errors after upgrading to Astro 5.0.5 + SL 0.30.1

### ISSUE THREAD

**Issue by NeilJS** [HiDeoo/starlight-links-validator#76]
### Describe the bug

After upgrading to the new Astro, I am getting "invalid link" errors on some - but not all - pages that previously passed the validation.

- Seems to be affecting .mdx but not .md files.
- I cannot see anything wrong with the invalid links.
- I can copy and paste the link to see that the page exists in the preview or build.

### To Reproduce

1. Before upgrading to Astro 5+, ensure at least one page is .mdx format. 
2. Run the link validator; confirm all links pass. 
3. Upgrade Astro to 5+.
4. Run the link validator again. Get 'invalid link' errors?

### Expected behavior

Valid links should not generate 'invalid link' errors, whether they are on .md or .mdx pages.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the report.

This plugin is not yet compatible with Starlight 0.30 and Astro 5. I'm currently working on it and it should be available in the next few days.

**Comment by NeilJS** [comment]
Marvellous. Thank you for the update.

**Comment by joshka** [comment]
Same - a workaround that worked in https://github.com/ratatui/ratatui-website/pull/795 was to remove the leading / from the links. This shouldn't be necessary, but hopefully that helps diagnose the underlying issue.

Commit https://github.com/ratatui/ratatui-website/pull/795/commits/b7e1ccbc5687e2194bf084a977802fbe872cac1e

**Comment by garysassano** [comment]
I have the same issue.

**Comment by HiDeoo** [comment]
This should now be fixed in the version [0.14.0](https://github.com/HiDeoo/starlight-links-validator/releases/tag/starlight-links-validator%400.14.0) of the plugin that I just published.

I highly recommend to take a look at the changes for potential breaking changes or known issues.

**Comment by garysassano** [comment]
Upgrading from `0.12.4` to `0.14.0` reduced my link validation errors from 10 to 4, but the issue still isn't entirely resolved.

I was able to pinpoint the root cause of the problem.
The issue arises when you have an `index.md` file that contains only frontmatter and no additional content.  

For example, if your file looks like this:  

**./src/content/docs/bugs/index.md**
```md
---
title: 🐞 Bugs
---
```

And you reference it in an `.mdx` file like `[Bugs](/bugs/)`, then the link validation fails.

However, if you modify the file to include content, like this:

**./src/content/docs/bugs/index.md**
```md
---
title: 🐞 Bugs
---
foobar
```

The validation error is resolved.

**Comment by HiDeoo** [comment]
> The issue arises when you have an `index.md` file that contains only frontmatter and no additional content.

This seems to be an Astro regression tracked in https://github.com/withastro/astro/issues/12800
